#pragma config(Sensor, dgtl11, driveE,         sensorQuadEncoder)
#pragma config(Motor,  port1,           Ldrive,        tmotorVex393HighSpeed_HBridge, openLoop, reversed)
#pragma config(Motor,  port10,          Rdrive,        tmotorVex393HighSpeed_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Global variables
int ticksPerRotation = 360;
int wheelDiameter = 3.25; //3.25" wheels
int circ = PI*wheelDiameter;

//Inputs inches, outputs proper tick value needed
int inchesToTicks(int inches){
	return (inches/circ)*ticksPerRotation;
}

//The actual move straight function that runs the motors
void moveStraight(int inches, int speed, int direction){
	//Resets the encoder value
	SensorValue[driveE] = 0;
	int currentValue = 0;
	int targetTicks = inchesToTicks(inches);
	inchesToTicks(inches);
	while(abs(currentValue)<targetTicks){
		motor[Ldrive] = speed*direction;
		motor[Rdrive] = speed*direction;
		currentValue = SensorValue[driveE]; //Constantly reads the encoder value
	}
	motor[Ldrive] = 0; //Stops drive motors after target it reached
	motor[Rdrive] = 0;
}

//Turn function that either turns 90 degrees cw or ccw depending on direction input
void turn(int direction){
	SensorValue[driveE] = 0;
	int currentValue = 0;
	int targetTicks = 240;
	while(abs(currentValue)<targetTicks){
		motor[Ldrive] = -40*direction;
		motor[Rdrive] = 40*direction;
		currentValue = SensorValue[driveE];
	}
	motor[Ldrive] = 0;
	motor[Rdrive] = 0;
}

//Main loop, program starts here
task main(){
	//Loops in a square
	while(1){
		moveStraight(24,60,1);
		wait1Msec(500);
		turn(1);
		wait1Msec(500);
	}
}
